services:
  monocker:
    container_name: monocker
    image: monocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # Optional label to preface messages. Handy if you are running multiple versions of Monocker
      SERVER_LABEL: "Dev"
      # Optional avatar image URL to add to messages. Handy if you are running Monocker on different machines
      # -> ONLY supported by discord, slack & ntfy
      SERVER_AVATAR: "https://content.invisioncic.com/u329766/monthly_2024_05/monocker.png.ba5ffdb390b627097d2a53645cf87350.png"
      # [Optional] - Set this value to a docker socket URL, if you want to connect to docker this way. Leave it blank or omit it otherwise
      # DOCKER_HOST: 'tcp://192.168.1.134:2375'

      # Specify the messaging platform and details, or leave blank if only wanting container logs (pick one only)
      # MESSAGE_PLATFORM: 'telegram@your_bot_id@your_chat_id'
      # MESSAGE_PLATFORM: 'pushbullet@your_api_key@your_device_id'
      # MESSAGE_PLATFORM: 'pushover@your_user_key@your_app_api_token'
      MESSAGE_PLATFORM: "discord@webhook_url"
      # MESSAGE_PLATFORM = apprise@apprise_url@config_id@tag
      # MESSAGE_PLATFORM: 'gotify@server@app_token'
      # MESSAGE_PLATFORM: 'ntfy@topic_title'
      # MESSAGE_PLATFORM: 'slack@bot_user_oauth_token@your_chat_id'
      # For Matrix, add the userid 'without' the leading @ sign. Values are server, userid, access-token, room-id
      # MESSAGE_PLATFORM = matrix@https://matrix.org@user:matrix.org@access-token@room-id:matrix.org
      # MESSAGE_PLATFORM: ''

      # Optional - includes or excludes specified containers - default behaviour is false
      # If missing or set to false (default), any containers with a "monocker.enable: 'false'" label will be excluded, and all others monitored.
      # If set to true, only containers with a "monocker.enable: 'true'" label will be included.
      LABEL_ENABLE: "false"
      # Optional - only show when container state changes to being offline (paused, exited, running (unhealthy), or dead) - default is false
      ONLY_OFFLINE_STATES: "false"
      # [Optional] - Regardless of any other settings, you can ignore or include 'exited'
      EXCLUDE_EXITED: "false"
      # [Optional] - Set the poll period in seconds. Defaults to 10 seconds, which is also the minimum.
      PERIOD: 30
      # [Optional] - Suppress startup messages from being sent. Default is false
      DISABLE_STARTUP_MSG: "false"

      ## ADVANCED NTFY SETTINGS
      # CUSTOM_NTFY_SERVER: 'https://ntfy.yourdomain.net' # use your own NTFY server
      # NTFY_USER: 'user' # use a username and password to login (on ntfy.sh or your own server)
      # NTFY_PASS: 'psw'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
